apiVersion: v1
kind: Service
metadata:
  name: nginx-server-svc
  namespace: nginx-ns
spec:
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30119
  selector:
    app: nginx-server
  type: NodePort